#set -x
BASH_DIR=$(dirname "${BASH_SOURCE[0]}")
source "$BASH_DIR"/pd_bucket.sh
source "$BASH_DIR"/pd_env.sh

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib

export VLLM_GPU_MEMORY_UTILIZATION=0.9
export VLLM_GRAPH_RESERVED_MEM=0.2
export VLLM_GRAPH_PROMPT_RATIO=0

# enable delayed samping on decode
export VLLM_DELAYED_SAMPLING="true"

# params
#model_len=16384
#max_num_batched_tokens=16384
#max_num_seqs=512
#input_min=2048
#input_max=3584
#output_max=1024

model_len=40960
max_num_batched_tokens=40960
max_num_seqs=64
input_min=3500
input_max=3500
output_max=1000

unset VLLM_PROMPT_BS_BUCKET_MIN VLLM_PROMPT_BS_BUCKET_STEP VLLM_PROMPT_BS_BUCKET_MAX
unset VLLM_PROMPT_SEQ_BUCKET_MIN VLLM_PROMPT_SEQ_BUCKET_STEP VLLM_PROMPT_SEQ_BUCKET_MAX
unset VLLM_DECODE_BS_BUCKET_MIN VLLM_DECODE_BS_BUCKET_STEP VLLM_DECODE_BS_BUCKET_MAX
unset VLLM_DECODE_BLOCK_BUCKET_MIN VLLM_DECODE_BLOCK_BUCKET_STEP VLLM_DECODE_BLOCK_BUCKET_MAX

set_bucketing



export VLLM_DECODE_BS_BUCKET_STEP=1
export VLLM_DECODE_BLOCK_BUCKET_STEP=2

export VLLM_PROMPT_BS_BUCKET_MIN=1
export VLLM_PROMPT_BS_BUCKET_STEP=1
export VLLM_PROMPT_BS_BUCKET_MAX=1
export VLLM_PROMPT_SEQ_BUCKET_MIN=1
export VLLM_PROMPT_SEQ_BUCKET_STEP=128
export VLLM_PROMPT_SEQ_BUCKET_MAX=1

echo VLLM_PROMPT_BS_BUCKET_MIN:$VLLM_PROMPT_BS_BUCKET_MIN, VLLM_PROMPT_BS_BUCKET_STEP:$VLLM_PROMPT_BS_BUCKET_STEP, VLLM_PROMPT_BS_BUCKET_MAX:$VLLM_PROMPT_BS_BUCKET_MAX
echo VLLM_PROMPT_SEQ_BUCKET_MIN:$VLLM_PROMPT_SEQ_BUCKET_MIN, VLLM_PROMPT_SEQ_BUCKET_STEP:$VLLM_PROMPT_SEQ_BUCKET_STEP, VLLM_PROMPT_SEQ_BUCKET_MAX:$VLLM_PROMPT_SEQ_BUCKET_MAX
echo VLLM_DECODE_BS_BUCKET_MIN:$VLLM_DECODE_BS_BUCKET_MIN, VLLM_DECODE_BS_BUCKET_STEP:$VLLM_DECODE_BS_BUCKET_STEP, VLLM_DECODE_BS_BUCKET_MAX:$VLLM_DECODE_BS_BUCKET_MAX
echo VLLM_DECODE_BLOCK_BUCKET_MIN:$VLLM_DECODE_BLOCK_BUCKET_MIN, VLLM_DECODE_BLOCK_BUCKET_STEP:$VLLM_DECODE_BLOCK_BUCKET_STEP, VLLM_DECODE_BLOCK_BUCKET_MAX:$VLLM_DECODE_BLOCK_BUCKET_MAX


echo " environments are reseted "

env | grep VLLM_PROMPT_BS
env | grep VLLM_PROMPT_SEQ
env | grep VLLM_DECODE_BS
env | grep VLLM_DECODE_BLOCK

export VLLM_SKIP_WARMUP=True
#unset VLLM_SKIP_WARMUP
#export PT_HPU_RECIPE_CACHE_CONFIG=/workspace/ww33_inc_fp8_d,false,16384
export PT_HPU_RECIPE_CACHE_CONFIG=/host/mnt/disk002/kf/recipe_cache/ww33_inc_fp8_d,false,16384

export VLLM_DP_SIZE=2
export VLLM_USE_V1=0
export VLLM_DP_MASTER_IP=10.239.129.81
export VLLM_DP_MASTER_PORT=25940
export VLLM_EP_SIZE=16

export PT_HPU_MOE_THRESHOLD=64

if [ "$INC_FP8" -eq 1 ]; then
  export QUANT_CONFIG="$BASH_DIR"/inc_fp8_tp1ep16.json
fi

